// server.js
const express = require("express");
const path = require("path");
const fs = require("fs-extra");
const PDFDocument = require("pdfkit");
const dotenv = require("dotenv");

dotenv.config();

const app = express();
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

const PDF_PORT = process.env.PORT || 5000;
const PUBLIC_URL = process.env.PUBLIC_URL || `http://localhost:${PDF_PORT}`;
const RECEIPTS_DIR = path.join(__dirname, "public", "receipts");
fs.ensureDirSync(RECEIPTS_DIR);

// Serve static files
app.use("/public", express.static(path.join(__dirname, "public")));

// Generate PDF receipt
import PDFDocument from "pdfkit";
import fs from "fs";
import path from "path";

export async function generateReceiptPDF(data) {
  return new Promise((resolve, reject) => {
    try {
      const RECEIPTS_DIR = path.join(process.cwd(), "public", "receipts");
      if (!fs.existsSync(RECEIPTS_DIR)) fs.mkdirSync(RECEIPTS_DIR, { recursive: true });

      const filename = `receipt_${data.merchant_reference || data.fort_id}.pdf`;
      const filePath = path.join(RECEIPTS_DIR, filename);
      const publicUrl = `/receipts/${filename}`;

      const doc = new PDFDocument({
        size: "A4",
        margin: 40,
      });

      const stream = fs.createWriteStream(filePath);
      doc.pipe(stream);

      const primaryColor = "#0C3C78"; // School theme color

      // -----------------------------------------------------------
      // Header with Logo
      // -----------------------------------------------------------
      if (data.logoPath && fs.existsSync(data.logoPath)) {
        doc.image(data.logoPath, 40, 40, { width: 90 });
      }

      doc
        .fontSize(20)
        .fillColor(primaryColor)
        .text("Alsson School – Payment Receipt", 150, 45);

      doc
        .fontSize(10)
        .fillColor("black")
        .text(`Date: ${data.date}`, 150, 75);

      doc.moveDown(2);

      // -----------------------------------------------------------
      // Section Title
      // -----------------------------------------------------------
      doc
        .fontSize(16)
        .fillColor(primaryColor)
        .text("Receipt Details", { underline: true });

      doc.moveDown(1.5);

      // -----------------------------------------------------------
      // Summary Box
      // -----------------------------------------------------------
      drawBoxTitle(doc, "Payment Summary");

      doc
        .fontSize(12)
        .fillColor("black")
        .text(`Parent Email: ${data.parentEmail}`)
        .moveDown(0.3)
        .text(`Amount Paid: ${Number(data.amount).toLocaleString()} EGP`)
        .moveDown(1);

      // -----------------------------------------------------------
      // Transaction Table
      // -----------------------------------------------------------
      drawBoxTitle(doc, "Transaction Information");

      const rows = [
        ["Transaction ID", data.fort_id],
        ["Order Reference", data.merchant_reference],
        ["Status", data.status],
        ["Message", data.response_message],
      ];

      drawTable(doc, rows, 12);

      // -----------------------------------------------------------
      // Footer
      // -----------------------------------------------------------
      doc.moveDown(3);
      doc
        .fontSize(10)
        .fillColor("#555")
        .text("This receipt is automatically generated by Alsson School Fees Payment System.")
        .moveDown(0.5)
        .text("If you have questions, contact: fees@alsson.com");

      doc.end();

      stream.on("finish", () => {
        resolve({ filePath, publicUrl });
      });
      stream.on("error", reject);
    } catch (err) {
      reject(err);
    }
  });
}

function drawBoxTitle(doc, title) {
  doc
    .moveDown(1)
    .fontSize(14)
    .fillColor("#0C3C78")
    .text(title, { underline: true })
    .moveDown(0.5);
}

function drawTable(doc, rows, fontSize = 12) {
  const startX = 40;
  let y = doc.y;

  const col1Width = 150;
  const col2Width = 350;
  const rowHeight = 22;

  doc.lineWidth(0.5);

  rows.forEach(([label, value]) => {
    // Draw background
    doc.rect(startX, y, col1Width + col2Width, rowHeight).stroke();

    // Label
    doc
      .fontSize(fontSize)
      .fillColor("#0C3C78")
      .text(label, startX + 5, y + 6);

    // Value
    doc
      .fontSize(fontSize)
      .fillColor("black")
      .text(String(value || ""), startX + col1Width + 15, y + 6, {
        width: col2Width - 20,
      });

    y += rowHeight;
  });

  doc.moveDown(2);
}


// Endpoint to generate receipt
app.post("/api/generate-receipt", async (req, res) => {
  try {
    const data = req.body;
    if (!data || !data.parentEmail || !data.amount) {
      return res.status(400).json({ error: "parentEmail and amount are required" });
    }

    const logoPath = path.join(__dirname, "assets", "newgiza-logo.jpg");
    const pdfInfo = await generateReceiptPDF({
      ...data,
      logoPath: fs.existsSync(logoPath) ? logoPath : undefined,
      date: data.date || new Date().toLocaleString(),
    });

    return res.json({ success: true, ...pdfInfo });
  } catch (err) {
    console.error(err);
    return res.status(500).json({ error: "Failed to generate receipt", details: err.message });
  }
});

// Endpoint to generate WhatsApp link
app.post("/api/generate-whatsapp-link", (req, res) => {
  try {
    const { schoolNumber = "201003828160", publicUrl, amount, fort_id, merchant_reference, parentEmail } = req.body;
    if (!publicUrl) return res.status(400).json({ error: "publicUrl required" });

    const msg = encodeURIComponent(
      `Payment Receipt Sent by Parent\nAmount: ${amount} EGP\nFort ID: ${fort_id}\nOrder Ref: ${merchant_reference}\nParent Email: ${parentEmail}\nDownload receipt: ${publicUrl}`
    );
    const waLink = `https://wa.me/${schoolNumber}?text=${msg}`;
    return res.json({ success: true, waLink });
  } catch (err) {
    console.error(err);
    return res.status(500).json({ error: "Failed to generate WhatsApp link", details: err.message });
  }
});



// ---------- GENERATE RECEIPT ----------
async function generateReceiptAndUploadToCloudinary(data) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 40, size: "A4" });
    const chunks = [];

    doc.on("data", (c) => chunks.push(c));

    doc.on("end", async () => {
      try {
        const pdfBuffer = Buffer.concat(chunks);

        const uploadStream = cloudinary.uploader.upload_stream(
          {
            resource_type: "raw",
            folder: "receipts",
            public_id: `receipt_${data.merchant_reference || data.fort_id}`
          },
          (err, result) => {
            if (err) return reject(err);

            resolve({
              success: true,
              publicUrl: result.secure_url,
              cloudinaryId: result.public_id,
              bytes: result.bytes
            });
          }
        );

        uploadStream.end(pdfBuffer);
      } catch (error) {
        reject(error);
      }
    });

    // Build PDF
    if (data.logoPath && fs.existsSync(data.logoPath)) {
      try {
        doc.image(data.logoPath, { fit: [160, 60] });
      } catch (e) {}
    }

    doc.fontSize(20).text("Payment Receipt", { align: "center" }).moveDown();
    doc.fontSize(12)
      .text(`Transaction ID: ${data.fort_id}`)
      .text(`Order Ref: ${data.merchant_reference}`)
      .text(`Amount: ${data.amount} EGP`)
      .text(`Parent Email: ${data.parentEmail}`)
      .text(`Date: ${data.date}`);

    doc.end();
  });
}


app.listen(PORT, () => console.log(`Server running on port ${PORT}`));



